/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./my-app/public/male_model_design/scene.gltf
Author: Digital Fashionwear (DF) (https://sketchfab.com/digitalfashionwear)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/male-model-design-c4a386c6c63a4a0e90d278f165b0f512
Title: Male Model Design
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'


export function Model(props) {
  const { nodes, materials } = useGLTF('http://localhost:8000/public/male_model_design/scene.gltf')
  return (
    <Canvas>
      <PerspectiveCamera name="camera" fov={40} near={10} far={1000} position={[10, 0, 50]} /> 
      <pointLight intensity={10} position={[100, 50, 100]} rotation={[-Math.PI / 2, 0, 0]} />     
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.Body} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.Body} />
        </group>
      </group>
    </Canvas>
  )
}

useGLTF.preload('/scene.gltf')
